stages:
  - build
  - test
  - prepare-deploy
  - deploy

variables:
  DOTNET_SDK_TAG: '10.0-noble'
  OBJECTS_DIRECTORY: 'artifacts/obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: './source/Cloudbb'
  MAJOR_VERSION: '0'
  MINOR_VERSION: '1'

.dotnet-base:
  image: "mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_TAG}"
  cache:
    # Per-stage and per-branch caching.
    key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    paths:
      # Main JSON file holding information about package dependency tree, packages versions,
      - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/project.assets.json'
      # Other NuGet and MSBuild related files. Also needed.
      - '$SOURCE_CODE_PATH/$OBJECTS_DIRECTORY/*/*.csproj.nuget.*'
      # Path to the directory where restored dependencies are kept.
      - '$NUGET_PACKAGES_DIRECTORY'
    policy: pull-push
  before_script: &base_before_script
    - dotnet restore "${SOURCE_CODE_PATH}" --packages "${NUGET_PACKAGES_DIRECTORY}"

build:
  extends: .dotnet-base
  stage: build
  before_script:
    - dotnet workload install wasm-tools
    - *base_before_script
  script:
    - dotnet build "${SOURCE_CODE_PATH}" --no-restore

unit-tests:
  extends: .dotnet-base
  stage: test
  script:
    - dotnet test "${SOURCE_CODE_PATH}/Cloudbb.Web.Tests" --no-restore

integration-tests:
  extends: .dotnet-base
  stage: test
  services:
    - name: postgres:18-trixie
      alias: postgres
      variables:
        POSTGRES_DB: postgres_e2e
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  before_script:
    - *base_before_script
    # set up RSA keys for JWT signing
    - apt-get update && apt-get install openssl -y
    - openssl genrsa -out /tmp/Cloudbb.Web.Tests.Integration.rsa_key.pem 2048
  script:
    - dotnet test "${SOURCE_CODE_PATH}/Cloudbb.Web.Tests.Integration" --no-restore

construct-version:
  image: debian:trixie-slim
  stage: prepare-deploy
  script:
    - |
      set -euvo pipefail
      export VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${CI_PIPELINE_IID}"
      echo "base version: ${VERSION}"
      mkdir -p app
      # check if we're on main or master. if not, append branch or tag name as pre-release label
      PRE_RELEASE_LABEL=""
      if [ "${CI_COMMIT_REF_SLUG}" != "main" ] && [ "${CI_COMMIT_REF_SLUG}" != "master" ]; then
        echo "non-main/master branch detected: ${CI_COMMIT_REF_SLUG}"
        PRE_RELEASE_LABEL="-${CI_COMMIT_REF_SLUG}"
      fi
      FULL_VERSION="${VERSION}${PRE_RELEASE_LABEL}"
      echo "${FULL_VERSION}" | tee app/version.txt
  artifacts:
    paths:
      - app

.deploy-image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: ["/busybox/sh", "-c"]
  needs:
    - construct-version
  script:
    - export VERSION="$(cat app/version.txt)"
    - echo "${VERSION}" | tee "${DOCKER_CONTEXT_PATH}/CI_VERSION_INFO"
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - |
      if [ "$CI_COMMIT_REF_SLUG" != "main" ]; then
        /kaniko/executor --context "${DOCKER_CONTEXT_PATH}" --dockerfile "${DOCKERFILE_PATH}" --destination "${IMAGE_NAME}:${VERSION}"
      else
        /kaniko/executor --context "${DOCKER_CONTEXT_PATH}" --dockerfile "${DOCKERFILE_PATH}" --destination "${IMAGE_NAME}:${VERSION}" --destination "${IMAGE_NAME}:latest"
      fi

# Use separate registry paths for different services
deploy-api:
  extends: .deploy-image
  variables:
    DOCKER_CONTEXT_PATH: "${SOURCE_CODE_PATH}"
    DOCKERFILE_PATH: "${SOURCE_CODE_PATH}/Cloudbb.Web/Dockerfile"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/api"

deploy-native-api:
  extends: .deploy-image
  variables:
    DOCKER_CONTEXT_PATH: "${SOURCE_CODE_PATH}"
    DOCKERFILE_PATH: "${SOURCE_CODE_PATH}/Cloudbb.Web.Aot/Dockerfile"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/api-native"

deploy-client:
  extends: .deploy-image
  variables:
    DOCKER_CONTEXT_PATH: "${SOURCE_CODE_PATH}"
    DOCKERFILE_PATH: "${SOURCE_CODE_PATH}/Cloudbb.Client/Dockerfile"
    IMAGE_NAME: "${CI_REGISTRY_IMAGE}/client"