<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>02764e65-d84b-4cdc-a049-1786ce0c9fbd</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.11">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
		<PackageReference Include="Wkg" Version="9.0.18075" />
		<PackageReference Include="Wkg.AspNetCore" Version="9.0.17799" />
		<PackageReference Include="Wkg.EntityFrameworkCore" Version="9.0.18636" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Data\Model\" />
	</ItemGroup>
</Project>
